### PR TITLE
Change file extension to be more intuitive; Enable execution as well

### PR DESCRIPTION
**Pull request by puhfessorp**
Hello,
When I first ran your script, I saw the extension "sh" and ran as
```sh focalgdm3.sh```
But this didn't correctly detect the codename "focal".
After noticing your shebang line, I changed the extension to bash to be more intuitive, and also added chmod +x so users can just rely on your shebang as well.
I hope this is useful to you. I love your script!

### CODE REVIEW

**Comment by puhfessorp** [comment]
Hey thanks for the thoughtful response. To be fair, I think a lot of scripts out there use the sh extension when bash is intended. Maybe at least the chmod would be useful without breaking things the way you want them. I can't speak for others but I personally go for direct execution when I see that sweet green highlight in an "ls".

**Comment by PRATAP-KUMAR** [comment]
Hi, I think there is no need for chmod when you run `bash focalgdm3.sh --set`. You mean avoiding bash is a good idea? Yes that may be good. Its users wish whether he want to chmod or not. Thats why did not do that. And also, the package `libglib2.0-dev` is users wish. I came across some who dont want to install any additional packages to get some tweaks. Thank You.

**Comment by puhfessorp** [comment]
Yeah that's what I mean. Sometimes the lazy/easy way is just to execute the script without the interpreter, like:
```./focalgdm3.sh```
I do it this way a lot for my own scripts.

**Comment by PRATAP-KUMAR** [comment]
Hi, I agree with you about `chmod +x`, can you edit your pull request to include only `chmod+x` step and not the file name change. I am sorry about the delay. I just got clarity on `chomod +x` concept. The second one you know the reason, I mean the name change of the file as we discussed earlier. Thank You..

**Comment by puhfessorp** [comment]
Okay I sent you a new one

**Pull request closed without merging**
